<div class="entry-edit">
	<h4>123</h4>
</div>
<!--<div class="left">
	<h2>Products</h2>
	<div class="product-entry">
		<h3>Product AAA</h3>
	</div>
	<h2>Blog</h2>
	<div class="blog-entry">
		<h3>Blog AAA</h3>
	</div>
</div>

<div class="right">
	
</div>

<script type="text/javascript">
	jQuery(function() {
		var formKey = "<?php echo $this->getFormKey();?>";
		jQuery.ajax({
			url: "<?php echo $this->getCurlPageUrl();?>",
			type: "POST",
			data: {
				url:"http://www.magentogarden.com",
				form_key: formKey
			}
		});
	});
</script>
-->