<?php
$_products = $this -> getProducts();
?>

<div class="entry-edit">
	<div class="mg-left">
		<select size="100">
			<?php foreach ($_products as $_product): ?>
			<option value="<?php echo $_product['url']?>"><?php echo $_product['name']?></option>
			<?php endforeach;?>
		</select>
	</div>
	<div class="mg-right">
		<p class="notice">
			Click the product list on the left and wait a moment for our system analysis
		</p>
		<div class="slide-panel">
			<div class="select-content mg-section">
				<h3>Select Content</h3>
				<div class="mg-content"></div>
			</div>
			<div class="yahoo-result mg-section">
				<h3>Keywords</h3>
				<div class="mg-content"></div>
			</div>
		</div>
	</div>
</div>
<div class="preload">Loading ...</div>

<style>
	.entry-edit .mg-left { float: left; width: 30%; height: 500px; border-right: 1px solid #ddd; padding-right: 10px; }
	.entry-edit .mg-left select { width: 100%; height: 100%;}
	.entry-edit .notice {  }
	.entry-edit .mg-right { float: left; width: 66%; padding-left: 10px; }
	.entry-edit .mg-right .slide-panel { display: none; }
	.entry-edit .mg-right .mg-section { margin-top: 10px; }
	.entry-edit .mg-right .yahoo-table { width: 100%; }
	.entry-edit .mg-right .yahoo-table thead td { font-weight: bold; }
	.entry-edit .mg-right .yahoo-table td { padding: 2px; }
	.preload { background: url("<?php echo $this->getSkinUrl('preloader.gif');?>") no-repeat scroll center center #fff; display: block; font-size: 13px; height: 45px; position: absolute; left: 39%; top: 40%; width: 230px; z-index: 10000; padding-top: 105px; position: fixed; border: 1px solid #ddd; border-radius: 10px; box-shadow: 2px 2px 5px #888888; text-align: center; display: none; }
</style>

<script type="text/javascript">
	var data;
	var showOverlay = function() {
		var black = "<div class='black-background' style='width: 100%; height: 100%; position: absolute; background-color: #000; opacity: 0.8; top:0; left:0; z-index:149;'></div>";
		jQuery('body').append(black);
		jQuery('.preload').show();
	};
	var hideOverlay = function() {
		jQuery('.black-background').remove();
		jQuery('.preload').hide();
	};
	
	jQuery(function() {
		var formKey = "<?php echo $this->getFormKey();?>";
		
		var curlpage = function (url, callback) {
			jQuery.ajax({
				url: "<?php echo $this->getCurlPageUrl();?>",
				type: "POST",
				data: {
					url: url,
					form_key: formKey
				}
			}).success(function(response) { callback(response); });
		};
		
		jQuery('.entry-edit .mg-left select').click(function () {
			var url = jQuery(this).val();
			showOverlay();
			curlpage(url, function(response) {
				response = jQuery.parseJSON(response);
				jQuery('.entry-edit .mg-right .select-content .mg-content').html(response.content);
				jQuery('.entry-edit .mg-right .yahoo-result .mg-content').html(response.yahoo);
				jQuery('.entry-edit .mg-right .slide-panel').show();
				hideOverlay();
			});
		});
		
		
	});
</script>