<?php if (Mage::helper('seosuite')->isBlogEnabled()): ?>
<meta property="og:type" content='article'>
<meta property="og:title" content='<?php echo $this->getBlogTitle();?>'>
<meta property="og:article:author" content='<?php echo $this->getBlogAuthor();?>'>
<meta property="og:article:published_time" content='<?php echo $this->getBlogPublishedTime();?>'>
<meta property="og:article:modified_time" content='<?php echo $this->getBlogUpdateTime();?>'>
<meta property="og:article:tag" content='<?php echo $this->getBlogTags();?>'>
<?php endif; ?>
